version: "3.8"
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'

  note-taking-service:
    container_name: note-taking-service
    image: note-taking-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_db: {}